/-
Copyright (c) 2026 Robin Carlier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Robin Carlier
-/

import Mathlib.GroupTheory.FreeAbelianGroup
import Mathlib.Algebra.Field.Defs
import Mathlib.Tactic.Ring
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# The Grothendieck-Witt ring of a field

In this file, we define the Grothendieck-Witt group a field `F` as a quotient
of `FreeAbelianGroup F`. Note that since we take the presentation by generators
and relation as a definition, the object we construct has a priori no link
with the theory of symmetric bilinear forms.
-/
section pre_GW
/-! Boilerplate to define the Grothendieck-Witt group of a field
through its presentation by generators and relations. -/

end pre_GW

section GrothendieckWitt

section GW_def
variable (F : Type*) [Field F]

/-- The generating predicate for the relations defining the Grothendieck-Witt group -/
@[mk_iff, grind]
inductive GWRelation : FreeAbelianGroup F → Prop where
  | gw0 (n : ℤ) : GWRelation (n * .of 0)
  | gw1 (u v : F) : (u ≠ 0) → (v ≠ 0) → GWRelation (.of u - .of (u * v^2))
  | gw2 (u : F) :
      (u ≠ 0) → GWRelation ((1 + .of (-1)) - (.of u + .of (-u)))
  | gw3 (u v : F) :
      (u ≠ 0) → (v ≠ 0) → (u + v ≠ 0) →
        GWRelation ((.of u + .of v) - (.of (u + v) + .of (u * v * (u + v))))

/-- The generating set for the relations defining the Grothendieck-Witt group -/
abbrev GWSet := { t | GWRelation F t }

-- TODO: split this prooof with sub-lemmas
/-- The ideal generated by the Grothendieck-Witt relations.
The proof of the `smul_mem` field is a bit of a long proof,
because it relies on the fact that some of the relations decompose as sums
of other relations when multiplied on the left.
Proving directly that this is an ideal is the more direct way to make
it so that the quotient has a commutative ring structure. -/
abbrev GWIdeal : Ideal (FreeAbelianGroup F) where
  __ := AddSubgroup.closure <| GWSet F
  smul_mem' := by
    intros c y hy
    rw [AddSubgroup.mem_carrier] at hy ⊢
    revert c
    refine AddSubgroup.closure_induction (hx := hy) ?_ ?_ ?_ ?_
    · intros x hx c;
      simp only [Set.mem_setOf_eq, gWRelation_iff, ne_eq, exists_and_left] at hx
      rcases hx with h0 | h1 | h2 | h3
      · rcases h0 with ⟨n, hn⟩
        rw [hn];
        induction c using FreeAbelianGroup.induction_on with
          | zero => simp
          | of c =>
            rw [smul_eq_mul, mul_comm, ← FreeAbelianGroup.ofMulHom_coe,
              mul_assoc, ← map_mul, zero_mul]
            apply Set.mem_of_subset_of_mem AddSubgroup.subset_closure
            dsimp [GWSet]
            exact .gw0 _
          | neg c hc => rwa [neg_smul, neg_mem_iff]
          | add x y hx hy =>
            rw [add_smul]
            apply AddSubgroup.add_mem <;> assumption
      · rcases h1 with ⟨u, ⟨v, hu, ⟨hv, hx⟩⟩⟩;
        induction c using FreeAbelianGroup.induction_on with
          | zero => simp
          | of c =>
            rw [hx]; have hh : FreeAbelianGroup.of c = .of c := by rfl;
            rw [smul_eq_mul, hh, mul_sub, ← FreeAbelianGroup.of_mul,
              ← FreeAbelianGroup.of_mul, ← mul_assoc];
            by_cases hc : c = 0;
            · simp [hc, zero_mul, zero_mul, sub_self]
            apply Set.mem_of_subset_of_mem AddSubgroup.subset_closure
            dsimp
            grind
          | neg c hc      => rwa [neg_smul, neg_mem_iff]
          | add x y hx hy =>
            rw [add_smul]
            apply AddSubgroup.add_mem <;> assumption
      · rcases h2 with ⟨u, ⟨hu, hx⟩⟩;
        induction c using FreeAbelianGroup.induction_on with
          | zero => simp
          | of c =>
            rw [hx, smul_eq_mul, mul_sub, mul_add, mul_add]
            simp_rw [← FreeAbelianGroup.of_mul, mul_neg, mul_one]
            by_cases hc : c = 0
            · rw [hc, zero_mul, sub_self]
              refine AddSubgroup.zero_mem _
            conv => arg 2; equals
               (1 + .of (-1) - ((.of (c * u) + .of (-(c * u))))) -
                 (1 + .of (-1) - ((.of (c) + .of (-c)))) => abel
            apply AddSubgroup.sub_mem <;>
            · apply Set.mem_of_subset_of_mem AddSubgroup.subset_closure
              grind
          | neg _ _        => rwa [neg_smul, neg_mem_iff]
          | add x y hx hy  =>
            rw [add_smul]
            apply AddSubgroup.add_mem <;> assumption
      · rcases h3 with ⟨u, hu, v, hv, huv, rfl⟩
        induction c using FreeAbelianGroup.induction_on with
        | zero => simp
        | of c =>
          rw [smul_eq_mul, mul_sub, mul_add, mul_add]
          simp_rw [← FreeAbelianGroup.of_mul]
          by_cases hc : c = 0;
          · simp [hc]
          rw [mul_add]
          have H :
            FreeAbelianGroup.of (c * u) + .of (c * v) -
              (.of (c * u + c * v) + .of (c* (u* v * (u + v)))) =
            (.of (c * u) + .of (c * v) - (.of (c * u + c * v) +
                .of ((c * u) * ( c* v) * (c * u + c * v))))
              - (.of (c * u * v * (u + v)) - .of ( c * u * v * (u + v) * c^2)) := by grind
          rw [H]
          apply AddSubgroup.sub_mem
          · apply Set.mem_of_subset_of_mem AddSubgroup.subset_closure
            apply GWRelation.gw3 <;> grind
          · apply Set.mem_of_subset_of_mem AddSubgroup.subset_closure
            grind
        | neg _ _ => rwa [neg_smul, neg_mem_iff]
        | add x y hx hy =>
          rw [add_smul]
          apply AddSubgroup.add_mem <;> assumption
    · simp
    · intros x y hx hy hc hc' c
      rw [smul_add]
      apply AddSubgroup.add_mem <;> grind
    · intros x hx hc c
      rw [smul_neg, neg_mem_iff]
      grind

/-- The Grothendieck-Witt of `F`. Note that we define it with generators in relations,
so this object has (a priori) no link to symmetric bilinear forms. -/
@[irreducible]
def GW := (FreeAbelianGroup F) ⧸ (GWIdeal F) deriving CommRing

end GW_def

namespace GW

variable {F : Type*} [Field F]

unseal GW in
/-- The quotient map from `FreeAbelianGroup F` to `GW F`. -/
@[irreducible]
def l₁ : FreeAbelianGroup F →+* GW F := Ideal.Quotient.mk _

unseal GW l₁ in
lemma surjective_l₁ : Function.Surjective (l₁ (F := F)) := Ideal.Quotient.mk_surjective

unseal GW l₁ in
lemma ker_l₁ : RingHom.ker l₁ = GWIdeal F := by
  dsimp [l₁]
  exact Ideal.mk_ker

/-- The multiplicative map taking an element of `F` to the corresponding generator of the
Grothendieck-Witt group. -/
abbrev l : F →* GW F := l₁.toMonoidHom.comp (FreeAbelianGroup.ofMulHom (α := F))

@[simp]
lemma l_apply (x : F) : l x = l₁ (.of x) := rfl

abbrev hyperbolic : GW F := 1 + l (-1 : F)

@[grind →]
lemma l₁_apply_eq_zero_of_mem_GWSet
    {x : FreeAbelianGroup F}
    (hx : x ∈ (GWSet F)) :
    l₁ x = (0 : GW F) := by
  suffices h : x ∈ RingHom.ker l₁ by exact h
  rw [ker_l₁]
  apply Set.mem_of_subset_of_mem AddSubgroup.subset_closure
  exact hx

lemma induction_grothendieck_witt {P : GW F → Prop} (z : GW F)
    (P0 : P 0)
    (P1 : ∀ c : F, P (l c))
    (Pn: ∀ c : F, P (l c) → P (-(l c)))
    (Pp: ∀ x y : GW F, (P x) → (P y) → P (x + y)) : P z := by
  obtain ⟨t, rfl⟩ := surjective_l₁ z
  induction t using FreeAbelianGroup.induction_on with
  | zero => simpa
  | of c => exact P1 c;
  | neg c hc =>
    rw [map_neg]
    exact Pn _ hc
  | add x y hx hy =>
    rw [map_add]
    exact Pp _ _ hx hy

lemma GW0 : l (0 : F) = 0 := by
  apply l₁_apply_eq_zero_of_mem_GWSet
  dsimp
  convert GWRelation.gw0 1
  grind

lemma GW1 (u : F) {v : F} (hv : v ≠ (0 : F)) : l u = l (u * v^2) := by
  by_cases! hu : u = 0
  · grind
  rw [← sub_eq_zero, l_apply, l_apply, ← map_sub]
  apply l₁_apply_eq_zero_of_mem_GWSet
  grind

lemma GW2 {a : F} (ha : a ≠ 0) : l a + l (-a) = .hyperbolic := by
  dsimp [GW.hyperbolic]
  rw [← map_one l₁]
  suffices h : l₁ (- FreeAbelianGroup.of a - .of (-a) + 1 + .of (-1)) = 0 by
    grind
  apply l₁_apply_eq_zero_of_mem_GWSet
  dsimp
  convert GWRelation.gw2 a
  grind

lemma GW3 {u v : F} (hu : u ≠ 0) (hv : v ≠ 0) (huv : u + v ≠ 0) :
    l u + l v = l (u + v) + l (u * v * (u + v)) := by
  dsimp
  suffices h :
      l₁ (FreeAbelianGroup.of u + .of v - .of (u + v) - .of (u * v * (u + v))) = 0 by
    grind
  apply l₁_apply_eq_zero_of_mem_GWSet
  dsimp
  convert GWRelation.gw3 u v
  grind

section rank

variable {F : Type*} [Field F] [DecidableEq F]
variable (x : F)

/-- The homomorphism that defines the rank morphism. It takes `0` to `0` and all other
elements to `1`. -/
noncomputable def preRank : FreeAbelianGroup F →+* ℤ :=
  letI e : F →* ℤ :=
    { toFun f := ite (f = 0) 0 1
      map_one' := by grind
      map_mul' := by grind }
  FreeAbelianGroup.liftMonoid e

@[simp, grind =] lemma preRank_of (f : F) : preRank (.of f) = if f = 0 then 0 else 1 := by
  simp [preRank]

lemma preRank_can_lift : ∀ x : (FreeAbelianGroup F), x ∈ GWIdeal F → preRank x = 0 := by
  intro x hx
  exact AddSubgroup.closure_induction (hx := hx) (by grind) (by grind) (by grind) (by grind)

/-- The rank morphism. It takes a generator `l x` to `1` if x ≠ 0. -/
noncomputable def rank : GW F →+* ℤ :=
  RingHom.liftOfSurjective l₁ surjective_l₁
    ⟨preRank, by
      intro t
      rw [ker_l₁]
      exact preRank_can_lift t⟩

@[simp, grind =] lemma rank_l (x : F) : rank (l x) = if x = 0 then 0 else 1 := by
  simp [rank, RingHom.liftOfSurjective_comp_apply]

@[simp, grind =] lemma rank_l_pos (x : F) (hx : x ≠ 0 := by grind) : rank (l x) = 1 := by
  grind

end rank

end GW

end GrothendieckWitt
