/-
Copyright (c) 2026 Robin Carlier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Robin Carlier
-/

import KMilnorWitt.Basic
import Mathlib.Algebra.FreeAlgebra
import Mathlib.Algebra.Field.Defs
import Mathlib.Algebra.RingQuot
import Mathlib.Tactic.FieldSimp

/-!
# Witt K-theory of a field

In this file, we define the Witt K-theory of a field `F` as a quotient
of `KMilnorWitt F`.
Just like `KMilnorWitt F`, we only define it as a (commutative) ring for now,
and we do not state anything about gradings.
-/

section rel_def

variable {F : Type*} [Field F]

/-- The relation defining `KWitt F` as a quotient of `KMilnorWitt F`.
It is the two-sided ideal generated by the hyperbolic element. -/
def wittRelation : KMilnorWitt F → KMilnorWitt F → Prop :=
  fun x y => ∃ t, (x - y) = .hyperbolic * t

@[grind =]
lemma wittRelation_iff (u v : KMilnorWitt F) :
    wittRelation u v ↔ ∃ t, (u - v) = .hyperbolic * t :=
  .rfl

@[grind _=_]
lemma wittRelation_symm (X Y : KMilnorWitt F) : wittRelation X Y ↔ wittRelation Y X := by
  suffices G : ∀ (t u : KMilnorWitt F), (wittRelation t u) → (wittRelation u t) by grind
  intro t u h1
  choose z hz using h1
  use -z
  calc u - t
    _ = - (t - u)           := by abel
    _ = - (.hyperbolic * z) := by rw [hz]
    _ = .hyperbolic * (-z)  := by rw [← mul_neg]

@[grind .]
lemma hyp_el_rel_zero_witt : wittRelation .hyperbolic (0 : KMilnorWitt F) := by
  rw [wittRelation_iff]
  use 1
  simp

lemma zero_rel_hyp_el_witt : wittRelation (0 : KMilnorWitt F) .hyperbolic := by grind

end rel_def

/-- The Witt K-theory of `F` as a quotient of the Milnor-Witt K-theory of `F` modulo
the relation generatod by the hyperbolic elmenent. -/
@[irreducible]
def KWitt (F : Type*) [Field F] := RingQuot <| wittRelation (F := F)
  deriving Ring

namespace KWitt

variable {F : Type*} [Field F]

unseal KWitt in
/-- The quotient map from Milnor-Witt K-theory to Witt K-theory. -/
@[irreducible]
def π : KMilnorWitt F →+* KWitt F := RingQuot.mkRingHom _

unseal KWitt π in
lemma π_surjective : Function.Surjective (π (F := F)) := RingQuot.mkRingHom_surjective _

open scoped KMilnorWitt
-- Defining the generating symbols of `KWitt F`.

-- TODO: setup notation for this symbol.
/-- The generating symbols in Witt K-theory. -/
def C (a : F) : KWitt F := π ⦃a⦄

-- TODO: setup notation for this symbol.
/-- The symbol corresponding to the action of the Grothendieck-Witt group. -/
def LL (a : F) : KWitt F := π ⟪a⟫

/-- The image of `η : KMilnorWitt F` in `KWitt F`. -/
def η : KWitt F := π .η

/-- The image of `ε : KMilnorWitt F` in `KWitt F`. -/
def ε : KWitt F := π .ε

section K_wittRelation
open scoped KMilnorWitt

variable {F : Type*} [Field F]

unseal KWitt π in
-- On reprend la plupart des relations de KMilnorWitt dans KWitt
lemma hyp_el_zero_witt : π .hyperbolic = (0 : KWitt F) := by
  rw [← map_zero π]
  apply RingQuot.mkRingHom_rel
  exact hyp_el_rel_zero_witt

unseal KWitt in
@[grind =]
lemma W0 : C (0 : F) = 0 := by
  unfold C
  suffices h: ⦃(0 : F)⦄ = 0 by
    rw [h]
    exact map_zero π
  exact KMilnorWitt.MW0

unseal KWitt in
@[grind =]
lemma W1 (a : F) : C a * C (1 - a) = 0 := by
  dsimp [C]
  rw [← map_mul]
  suffices h : ⦃a⦄ * ⦃1 - a⦄ = 0 by
    rw [h]
    exact map_zero π
  exact KMilnorWitt.MW1 a

unseal KWitt in
@[grind _=_]
lemma W2 {a : F} {b : F} (ha : a ≠ 0 := by grind) (hb : b ≠ 0 := by grind) :
    C (a * b) = C a + C b + η * C a * C b := by
  dsimp [C, η]
  rw [← map_add, ← map_mul, ← map_mul, ← map_add]
  congr
  exact KMilnorWitt.MW2 ha hb

unseal KWitt in
lemma W3 (a : F) : η * C a = C a * η := by
  unfold C
  unfold η
  rw [← map_mul, ← map_mul]
  congr 1
  exact KMilnorWitt.MW3 a

@[induction_eliminator, elab_as_elim]
lemma induction_KWitt {P : KWitt F → Prop}
    (h_grade0 : ∀ (n : ℤ), P (algebraMap ℤ (KWitt F) n))
    (h_grade1 : ∀ (a : F), P (C a))
    (h_grade2 : P η)
    (h_mul : ∀ a b, (P a) → (P b) → P (a * b))
    (h_add : ∀ a b, (P a) → (P b) → P (a + b))
    (a : KWitt F) : P a := by
  obtain ⟨x, rfl⟩ := π_surjective a
  induction x with
  | h_grade0 n => simpa only [map_intCast] using h_grade0 n
  | h_grade1 a => exact h_grade1 a
  | h_grade2 => exact h_grade2
  | h_mul a b _ _ => grind
  | h_add a b _ _ => grind

lemma η_center (X : KWitt F) : η * X = X * η := by
  induction X with
  | h_grade0 => rw [Algebra.commutes]
  | h_grade1 => rw [W3]
  | h_grade2 => rfl
  | h_mul a b ha hb => rw [← mul_assoc, ha, mul_assoc, hb, ← mul_assoc]
  | h_add a b ha hb => rw [mul_add, ha, hb, add_mul]

open KMilnorWitt
-- On commence les relations héritées de KMilnorWitt:

lemma C_mul_LL_1 {a b : F} (ha : a ≠ 0 := by grind) (hb : b ≠ 0 := by grind) :
    C (a * b) = C a + LL a * C b := by
  grind [C, LL, S_mul_eq_S_add_L_mul]

lemma C_mul_LL_2 {a b : F} (ha : a ≠ 0 := by grind) (hb : b ≠ 0 := by grind) :
    C (a * b) = C a * LL b + C b := by
  grind [C, LL, S_mul_eq_mul_L_add]

lemma LL_mul {a b : F} (ha : a ≠ 0 := by grind) (hb : b ≠ 0 := by grind) :
    LL (a * b) = LL a * LL b := by
  grind [LL]

@[grind =]
lemma LL_zero : LL (0 : F) = 1 := by grind [LL]

@[grind =]
lemma LL_one : LL (1 : F) = 1 := by grind [LL]

lemma LL_minus_one (a : F) : LL a - 1 = η * C a := by
  dsimp [LL, C, η]
  rw [← map_one π, ← map_sub, ← map_mul]
  congr
  exact L_minus_one a

lemma C_one : C (1 : F) = 0 := by grind [C]

lemma C_div {a b : F} (ha : a ≠ 0 := by grind) (hb : b ≠ 0 := by grind) :
    C (a / b) = C a - LL (a / b) * C b := by
  grind [C, LL, S_div]

lemma C_inv (a : F) : C (a⁻¹) = -LL (a⁻¹) * C a := by grind [C, LL]

lemma LL_neg {a : F} (ha : a ≠ 0 := by grind) : LL (-a) = - LL a := by
  grind [LL, hyperbolic_sum, hyp_el_zero_witt]

lemma ε_eq_one : ε = (1 : KWitt F) := by
  dsimp [ε]
  rw [ε_def, map_neg, ← LL, LL_neg]
  grind

instance : CommRing (KWitt F) where
  mul_comm X Y := by
    induction X with
    | h_grade0 => rw [Algebra.commutes]
    | h_grade1 X => induction Y with
        | h_grade0 => rw [Algebra.commutes]
        | h_grade1 Y =>
          conv_rhs => rw [← one_mul (C Y)]
          rw [← ε_eq_one]
          dsimp [C, ε]
          simp_rw [← map_mul]
          congr 1
          exact ε_comm_S X Y
        | h_grade2 => exact (η_center (C X)).symm
        | h_mul a b ha hb => rw [← mul_assoc, ha, mul_assoc, hb, ← mul_assoc]
        | h_add a b ha hb => rw [mul_add, ha, hb, add_mul]
    | h_grade2 => rw [η_center Y]
    | h_mul a b ha hb => rw [mul_assoc, hb, ← mul_assoc, ha, ← mul_assoc]
    | h_add a b ha hb => rw [add_mul, ha, hb, mul_add]

@[grind =]
lemma C_mul_C_neg (a : F) : C a * C (-a) = 0 := by
  dsimp [C]
  rw [← map_mul, ← map_zero π]
  congr 1
  exact S_mul_S_neg a

@[grind =]
lemma C_neg_mul_C (a : F) : C (-a) * C a = 0 := by
  dsimp [C]
  rw [← map_mul, ← map_zero π]
  congr 1
  exact S_neg_mul_S a

lemma C_mul_C_self (a : F) : C a * C a = C (-1) * C a := by
  dsimp [C]
  rw [← map_mul, ← map_mul]
  congr 1
  exact S_mul_S_self_eq_S_neg_one_mul_S a

@[grind =]
lemma C_mul_self (a : F) : C (a * a) = 0 := by
  by_cases! h : (a = 0)
  · grind
  calc C (a * a)
    _ = C a + C a + η * C a * C a              := by exact W2 h h
    _ = C a + C a + η * C (-1) * C a           := by grind [C_mul_C_self]
    _ = (2 + η * C (-1)) * C a                 := by grind
    _ = π (2 + KMilnorWitt.η * S (-1)) * C a   := by simp only [C, η, map_add, map_mul]
                                                     congr
                                                     rw [map_ofNat π 2]
    _ = π .hyperbolic * C a                    := by grind [hyperbolic]
    _ = 0 * C a                                := by rw [hyp_el_zero_witt]
    _ = 0                                      := by rw [zero_mul]

@[grind =]
lemma C_pow_two (a : F) : C (a^2) = 0 := by
  rw [pow_two]
  exact C_mul_self a

@[grind =]
lemma LL_mul_self (a : F) : LL (a * a) = 1 := by
  rw [← map_one π]
  grind [LL, L_mul_self]

lemma LL_pow_two (a : F) : LL (a^2) = 1 := by
  rw [pow_two]
  exact LL_mul_self a

lemma LL_mul_mul_self {a : F} (b : F) (ha : a ≠ 0 := by grind) :
    LL (b * (a * a)) = LL b := by
  dsimp [LL]
  congr 1
  rw [← mul_assoc]
  exact L_mul_mul_self b ha

lemma LL_mul_mul_self' {a : F} (b : F) (ha : a ≠ 0 := by grind) :
    LL (b * a^2) = LL b := by
  rw [pow_two]
  exact LL_mul_mul_self b ha

lemma LL_mul_self_mul {a : F} (b : F) (ha : a ≠ 0 := by grind) :
    LL (a * a * b) = LL b := by
  rw [mul_comm]
  exact LL_mul_mul_self b ha

lemma LL_mul_self_mul' (a : F) (b : F) (ha : a ≠ 0 := by grind) :
    LL (a^2 * b) = LL b := by
  rw [mul_comm]
  exact LL_mul_mul_self' b ha

end K_wittRelation

section GW_to_KWitt_C

variable {F : Type*} [Field F]

  -- Relation 1 in GW
@[grind =]
theorem C_mul_pow_two (u : F) {v : F} (hv : v ≠ 0 := by grind) :
    C (u * v^2) = C u := by
  by_cases! hu : u = 0
  · grind
  -- grind could also work instead of this calc block
  calc C (u * v^2)
    _ = C u + C (v^2) + η * C u * C (v^2) := by rw [W2]
    _ = C u + 0 + η * C u * 0             := by rw [C_pow_two]
    _ = C u                                 := by simp

-- Relation 2 in GW:
theorem C_add_neg {a : F} (ha : a ≠ 0 := by grind) :
    C a + C (-a) = C 1 + C (-1) := by
  rw [C_one, zero_add]
  symm
  calc C (-1)
    _ = C (-1 * (a * a))                      := by rw [← pow_two, C_mul_pow_two]
    _ = C (a * -a)                            := by ring_nf
    _ = C a + C (-a) + η * C a * C (-a)     := W2
    _ = C a + C (-a)                          := by grind [C_mul_C_neg]

@[grind _=_]
lemma C_add_compl (a : F) :
    C a + C (1 - a) = C (a * (1 - a)) := by
  by_cases! h0 : a = 0
  · simp [h0, C]
  by_cases! h1 : a = 1
  · grind
  symm
  calc C (a * (1 - a))
    _ = C a + C (1 - a) + η * C a * C (1 - a)  := W2 ..
    _ = C a + C (1 - a)                          := by grind [W1]

@[deprecated (since := "")] alias C_add_comp := C_add_compl

lemma LL_add_compl (a : F) :
    LL a + LL (1 - a) = 1 + LL (a * (1 - a)) := by
  by_cases! h0 : a = 0
  · simp [h0, LL]
  by_cases! h1 : a = 1
  · grind
  have H : - (LL a - 1) * (LL (1 - a) - 1) = 0 := by
    simp_rw [LL_minus_one]
    convert_to η^2 * (C a * C (1 - a)) = 0
    all_goals grind
  rw [← sub_eq_zero, LL_mul]
  -- grind also works here
  calc LL a + LL (1 - a) - (1 + LL a * LL (1 - a))
    _ = - (LL a - 1) * (LL (1 - a) - 1)             := by ring
    _ = 0                                           := by rw [H]

@[deprecated (since := "")] alias LL_add_comp := LL_add_compl

-- relation 3 in GW
theorem C_add {u v : F}
    (hu : u ≠ 0 := by grind) (hv : v ≠ 0 := by grind) (huv : u + v ≠ 0 := by grind) :
    C u + C v = C (u + v) + C ((u * v) * (u + v)) := by
  set a := u / (u + v) with ha
  have f0 : a * (1 - a) = (u * v) * (1 / (u + v))^2 := by grind
  have f1 : 1 - a = v / (u + v) := by grind
  have f2 : C a + C (1 - a) = C (u * v) := by grind
  have f3 :
      C u + C v = C (u * v) + LL (u / (u + v)) * C (u + v) + LL (v / (u + v)) * C (u + v) := by
    grind [C_div]
  rw [f3]
  calc C (u * v) + LL (u / (u + v)) * C (u + v) + LL (v / (u + v)) * C (u + v)
    _ = C (u * v) + LL a * C (u + v) + LL (1 - a) * C (u + v)   := by grind
    _ = C (u * v) + C (u + v) * (LL a + LL (1 - a))             := by grind
    _ = C (u * v) + C (u + v) * (1 + LL (a * (1 - a)))          := by rw [LL_add_compl]
    _ = C (u * v) + C (u + v) + LL (a * (1 - a)) * C (u + v)    := by grind
    _ = C (u * v) + C (u + v) + LL (u * v) * C (u + v)          := by rw [f0, LL_mul_mul_self']
    _ = C (u + v) + C ((u * v) * (u + v)) := by grind [C_mul_LL_1 (a := u * v) (b:= u + v)]

end GW_to_KWitt_C

end KWitt
